/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("com.gradle.develocity") version("3.17.6")
}

develocity {
    server = "https://ge.gradle.org"
}

rootProject.name = "multi-version-test-plugin"
include("common")
include("plugin-8.9")
include("plugin-9.0")
